# Generated by Django 5.1.4 on 2025-07-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('base_currency_symbol', models.CharField(max_length=10)),
                ('formal_name', models.CharField(max_length=255)),
                ('financial_year_start', models.DateField()),
                ('books_start_date', models.DateField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.country')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.state')),
            ],
        ),
    ]
