# Generated by Django 5.1.4 on 2025-07-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(max_length=50, null=True)),
                ('assessee_of_other_territory', models.BooleanField(default=False)),
                ('gstin_uin', models.CharField(blank=True, max_length=20, null=True)),
                ('periodicity_gstr1', models.CharField(max_length=100, null=True)),
                ('kerala_flood_cess', models.BooleanField(default=False)),
                ('gst_username', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_of_filing', models.CharField(max_length=200, null=True)),
                ('einvoice_applicable', models.BooleanField(default=False)),
                ('einvoice_applicable_from', models.DateField(blank=True, null=True)),
                ('invoice_bill_from_place', models.CharField(blank=True, max_length=100, null=True)),
                ('ewaybill_applicable', models.BooleanField(default=False)),
                ('ewaybill_applicable_from', models.DateField(blank=True, null=True)),
                ('ewaybill_interstate', models.BooleanField(default=False)),
                ('create_another_registration', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.state')),
            ],
        ),
    ]
