# Generated by Django 5.1.4 on 2025-07-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0003_gstdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_sac_details', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('taxability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('create_summary_for', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_length', models.IntegerField(blank=True, null=True)),
                ('show_gst_advances', models.BooleanField(default=False)),
                ('update_gst_status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
