# Generated by Django 5.1.4 on 2025-07-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0005_tdsdeductordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSCollectorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_eduction_collection_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('collector_type', models.CharField(blank=True, max_length=100, null=True)),
                ('collector_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('alter_person_responsible', models.BooleanField(default=False)),
                ('ignore_it_exemption_limit', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
