# Generated by Django 5.1.4 on 2025-07-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0006_tdscollectordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('interstate_sales_tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('alter_tax_rate_details', models.BooleanField(default=False)),
                ('define_vat_commodity', models.BooleanField(default=False)),
                ('deactivate_from', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.state')),
            ],
        ),
    ]
