# Generated by Django 5.1.4 on 2025-07-03 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0007_vatdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExciseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_type', models.CharField(max_length=100, null=True)),
                ('ecc_number', models.CharField(max_length=100, null=True)),
                ('set_alter_tariff', models.BooleanField(default=False)),
                ('define_tariff_masters', models.BooleanField(default=False)),
                ('deactivate_from', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.state')),
            ],
        ),
    ]
