# Generated by Django 5.1.4 on 2025-07-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0008_excisedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, null=True)),
                ('organisation_type', models.CharField(max_length=100, null=True)),
                ('set_alter_service_tax', models.BooleanField(default=False)),
                ('define_service_category_masters', models.BooleanField(default=False)),
                ('reverse_charge_applicable', models.BooleanField(default=False)),
                ('deactivate_from', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
