# Generated by Django 5.1.4 on 2025-07-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0009_servicetaxdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('service_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('education_cess', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('secondary_education_cess', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('swachh_bharat_cess', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('krishi_kalyan_cess', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
