# Generated by Django 5.1.4 on 2025-07-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0010_servicetaxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatutoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_company_code', models.CharField(max_length=100)),
                ('pf_account_group_code', models.CharField(blank=True, max_length=100, null=True)),
                ('pf_security_code', models.CharField(blank=True, max_length=100, null=True)),
                ('esi_company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('esi_branch_office', models.CharField(blank=True, max_length=100, null=True)),
                ('esi_working_days', models.PositiveIntegerField(blank=True, null=True)),
                ('nps_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nps_branch_office_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tan', models.CharField(blank=True, max_length=100, null=True)),
                ('tan_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('income_class_circle', models.CharField(blank=True, max_length=100, null=True)),
                ('deductor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('deductor_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('person_responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('son_daughter_of', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
