# Generated by Django 5.1.4 on 2025-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0013_alter_companyaddress_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_another', models.BooleanField(default=False)),
            ],
        ),
    ]
