# Generated by Django 5.1.4 on 2025-07-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0014_merchantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company'),
        ),
    ]
