# Generated by Django 5.1.4 on 2025-07-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0015_merchantprofile_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TDSCollectorDetails',
            new_name='TCSCollectorDetails',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='base_currency_symbol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='books_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='data_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='financial_year_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='formal_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mailing_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.state'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CompanyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_accounts', models.BooleanField(default=False)),
                ('enable_bill_wise_entry', models.BooleanField(default=False)),
                ('enable_cost_centres', models.BooleanField(default=False)),
                ('enable_interest_calculations', models.BooleanField(default=False)),
                ('maintain_inventory', models.BooleanField(default=False)),
                ('integrate_accounts_inventory', models.BooleanField(default=False)),
                ('enable_multiple_price_levels', models.BooleanField(default=False)),
                ('enable_batches', models.BooleanField(default=False)),
                ('maintain_expiry_for_batches', models.BooleanField(default=False)),
                ('enable_job_order_processing', models.BooleanField(default=False)),
                ('enable_cost_tracking', models.BooleanField(default=False)),
                ('enable_job_costing', models.BooleanField(default=False)),
                ('use_discount_column', models.BooleanField(default=False)),
                ('use_actual_billed_qty_columns', models.BooleanField(default=False)),
                ('enable_gst', models.BooleanField(default=False)),
                ('alter_gst_details', models.BooleanField(default=False)),
                ('enable_tds', models.BooleanField(default=False)),
                ('enable_tcs', models.BooleanField(default=False)),
                ('enable_vat', models.BooleanField(default=False)),
                ('enable_excise', models.BooleanField(default=False)),
                ('enable_service_tax', models.BooleanField(default=False)),
                ('enable_browser_access', models.BooleanField(default=False)),
                ('enable_remote_access', models.BooleanField(default=False)),
                ('maintain_payroll', models.BooleanField(default=False)),
                ('enable_payroll_statutory', models.BooleanField(default=False)),
                ('enable_payment_request', models.BooleanField(default=False)),
                ('enable_multiple_address', models.BooleanField(default=False)),
                ('mark_modified_vouchers', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
