# Generated by Django 5.1.4 on 2025-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0017_currentdate_daterange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterange',
            name='date_range',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
