# Generated by Django 5.1.4 on 2025-07-04 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0018_alter_daterange_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.state'),
        ),
    ]
