# Generated by Django 5.1.4 on 2025-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0022_tallyvaultsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstratedetails',
            name='gst_rate_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
