# Generated by Django 5.1.4 on 2025-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0024_gsteffectivedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstratedetails',
            old_name='classification',
            new_name='application_from',
        ),
        migrations.RenameField(
            model_name='gstratedetails',
            old_name='gst_rate_details',
            new_name='classification_gst',
        ),
        migrations.RenameField(
            model_name='gstratedetails',
            old_name='update_gst_status',
            new_name='update_gst_status_returns',
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='classification_hsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='gst_rate_details_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='interstate_threshold',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='intrastate_threshold',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='threshold_includes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstratedetails',
            name='update_gst_status_vouchers',
            field=models.BooleanField(default=False),
        ),
    ]
