# Generated by Django 5.1.4 on 2025-07-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0025_rename_classification_gstratedetails_application_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
