# Generated by Django 5.1.4 on 2025-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0026_gstsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstsettings',
            name='return_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
