# Generated by Django 5.1.4 on 2025-07-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0027_alter_gstsettings_return_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstsettings',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company'),
        ),
    ]
