# Generated by Django 5.1.4 on 2025-07-10 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0029_tdspersonresponsibledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('hsn_source', models.CharField(blank=True, max_length=128, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=128, null=True)),
                ('hsn_description', models.CharField(blank=True, max_length=128, null=True)),
                ('gst_rate_source', models.CharField(blank=True, max_length=128, null=True)),
                ('taxability_type', models.CharField(blank=True, max_length=128, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.classification')),
            ],
        ),
        migrations.CreateModel(
            name='SlabRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greater_than', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_upto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxability', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slab_rates', to='Tally_app.classification')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
