# Generated by Django 5.1.4 on 2025-07-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0031_tcspersonresponsibledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True)),
                ('tax_type', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_tax_rates', to='Tally_app.company')),
            ],
        ),
    ]
