# Generated by Django 5.1.4 on 2025-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0032_vattaxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='excisedetails',
            name='type_of_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
