# Generated by Django 5.1.4 on 2025-07-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0033_excisedetails_type_of_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExciseTariffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=200, null=True)),
                ('hsn_code', models.CharField(max_length=50, null=True)),
                ('reporting_uom', models.CharField(max_length=50, null=True)),
                ('valuation_type', models.CharField(max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excise_tariff_details', to='Tally_app.company')),
            ],
        ),
    ]
