# Generated by Django 5.1.4 on 2025-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0034_excisetariffdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excisetariffdetail',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='excisetariffdetail',
            name='rate_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
