# Generated by Django 5.1.4 on 2025-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0035_alter_excisetariffdetail_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaxrate',
            name='compute_tax_liability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetaxrate',
            name='is_monthly_format',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
