# Generated by Django 5.1.4 on 2025-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0036_servicetaxrate_compute_tax_liability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='registered_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
