# Generated by Django 5.1.4 on 2025-07-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0038_newusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_user_access', models.BooleanField(default=False)),
                ('email_for_browser_access', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_tally_audit', models.BooleanField(default=False)),
                ('disallow_educational_mode', models.BooleanField(default=False)),
                ('add_users_after_saving', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tally_app.company')),
            ],
        ),
    ]
