# Generated by Django 3.2.25 on 2025-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0039_securitysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaxdetails',
            name='compute_tax_liability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicetaxdetails',
            name='is_monthly_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
