# Generated by Django 5.1.1 on 2025-08-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0040_auto_20250711_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reserve_items', models.BooleanField(default=False)),
                ('non_reserve_items', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('formal_name', models.CharField(max_length=100)),
                ('iso_currency_code', models.CharField(max_length=10)),
                ('number_of_decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('show_amount_in_millions', models.BooleanField(default=False)),
                ('suffix_symbol_to_amount', models.BooleanField(default=False)),
                ('add_space_between_amount', models.BooleanField(default=False)),
                ('word_amount_adter_decimal', models.CharField(blank=True, max_length=50, null=True)),
                ('decimal_places_for_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListofGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfVoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Scenario name for reference', max_length=100, null=True)),
                ('include_actuals', models.BooleanField(default=False, help_text='Whether to include actual transactions')),
                ('exclude', models.ManyToManyField(blank=True, help_text='Voucher types excluded from scenario', related_name='excluded_from_scenarios', to='Tally_app.listofvouchertype')),
                ('include', models.ManyToManyField(blank=True, help_text='Voucher types included in scenario', related_name='included_in_scenarios', to='Tally_app.listofvouchertype')),
            ],
        ),
    ]
