# Generated by Django 5.1.1 on 2025-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0041_costcategory_currency_listofgroups_listofvouchertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateOfExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_date', models.DateField(blank=True, null=True)),
                ('standard_specified_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('selling_date', models.DateField(blank=True, null=True)),
                ('selling_last_voucher_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('selling_specified_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('buying_date', models.DateField(blank=True, null=True)),
                ('buying_last_voucher_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('buying_specified_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
    ]
