# Generated by Django 5.1.1 on 2025-08-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0042_rateofexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateofexchange',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rateofexchange',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rateofexchange',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_of_exchange', to='Tally_app.currency'),
        ),
    ]
