# Generated by Django 5.1.1 on 2025-08-27 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0043_remove_rateofexchange_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateofexchange',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='Tally_app.currency'),
        ),
    ]
