# Generated by Django 5.1.1 on 2025-08-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0044_alter_rateofexchange_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofvouchertype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
