# Generated by Django 5.1.1 on 2025-09-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0045_alter_listofvouchertype_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_godowns', to='Tally_app.godowns')),
            ],
        ),
    ]
