# Generated by Django 5.1.1 on 2025-09-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0046_godowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound')], default='simple', max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('formalname', models.CharField(blank=True, max_length=100, null=True)),
                ('uqc', models.CharField(blank=True, default='Not Applicable', max_length=100, null=True)),
                ('decimalno', models.PositiveIntegerField(default=0)),
                ('funit', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Unit')),
                ('sunit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conversion Factor')),
                ('tunit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Unit')),
            ],
        ),
    ]
