# Generated by Django 5.1.1 on 2025-09-10 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0048_alter_godowns_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godowns',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tally_app.godowns'),
        ),
    ]
