# Generated by Django 5.1.1 on 2025-09-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0049_alter_godowns_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godowns',
            name='under',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
