# Generated by Django 5.1.1 on 2025-09-11 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0050_alter_godowns_under'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='godowns',
            options={'verbose_name': 'Godown', 'verbose_name_plural': 'Godowns'},
        ),
        migrations.AddField(
            model_name='godowns',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='allow_storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='grouping_of_godowns',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='godowns',
            name='third_party_storage_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='godowns',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_godowns', to='Tally_app.godowns'),
        ),
        migrations.AlterModelTable(
            name='godowns',
            table='godown',
        ),
    ]
