# Generated by Django 5.1.1 on 2025-09-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tally_app', '0051_alter_godowns_options_godowns_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godowns',
            name='under',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
