from django.urls import path,re_path
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    path('',views.index,name='index'),
    path('Log_in/',views.Log_in,name='Log_in'),
    path('registration/',views.registration,name='registration'),
    path('Fun_login/',views.Fun_login,name='Fun_login'),
    path('userDashboard/',views.userDashboard,name='userDashboard'),
    path('masters_create/',views.masters_create,name='masters_create'),
    path('masters_alter/',views.masters_alter,name='masters_alter'),
    path('masters_chart_of_accounts/',views.masters_chart_of_accounts,name='masters_chart_of_accounts'),


    path('imported_bank_data/',views.imported_bank_data,name='imported_bank_data'),
    path('cheque_printing/',views.cheque_printing,name='cheque_printing'),
    path('post_dated_summary/',views.post_dated_summary,name='post_dated_summary'),
    path('deposit_slip/',views.deposit_slip,name='deposit_slip'),
    path('payment_advance/',views.payment_advance,name='payment_advance'),
    path('account_books_ledger/',views.account_books_ledger,name='account_books_ledger'),
    path('group_summary/',views.group_summary,name='group_summary'),
    path('group_vouchers/',views.group_vouchers,name='group_vouchers'),
    path('stock_item/',views.stock_item,name='stock_item'),
    path('location/',views.location,name='location'),
    path('stock_group_summary/',views.stock_group_summary,name='stock_group_summary'),
    path('stock_category_summary/',views.stock_category_summary,name='stock_category_summary'),
    path('stock_query/',views.stock_query,name='stock_query'),
    path('stock_group_analysis/',views.stock_group_analysis,name='stock_group_analysis'),
    path('stock_group_category/',views.stock_group_category,name='stock_group_category'),
    path('stock_item_analysis/',views.stock_item_analysis,name='stock_item_analysis'),
    path('group_analysis/',views.group_analysis,name='group_analysis'),
    path('ledger_analysis/',views.ledger_analysis,name='ledger_analysis'),
    path('transfer_analysis/',views.transfer_analysis,name='transfer_analysis'),
    path('ageing_analysis/',views.ageing_analysis,name='ageing_analysis'),
    path('cost_estimation/',views.cost_estimation,name='cost_estimation'),
    path('gst_rate_setup/',views.gst_rate_setup,name='gst_rate_setup'),
    path('validate_party/',views.validate_party,name='validate_party'),
    path('create_party/',views.create_party,name='create_party'),
    path('update_party_msme_details/',views.update_party_msme_details,name='update_party_msme_details'),
    path('pay_slip/',views.pay_slip,name='pay_slip'),
    path('pay_sheet/',views.pay_sheet,name='pay_sheet'),
    path('payment_advice/',views.payment_advice,name='payment_advice'),
    path('payroll_statement/',views.payroll_statement,name='payroll_statement'),
    path('employee_pay_head_breakup/',views.employee_pay_head_breakup,name='employee_pay_head_breakup'),
    path('pay_head_employee_breakup/',views.pay_head_employee_breakup,name='pay_head_employee_breakup'),
    path('employee_profile/',views.employee_profile,name='employee_profile'),

    path('create_company_page/',views.create_company_page,name='create_company_page'),
    path('create_new_state/',views.create_new_state,name='create_new_state'),
    path('create_new_country/',views.create_new_country,name='create_new_country'),
    path('company_features/',views.company_features,name='company_features'),
    path('gst_details/<int:company_id>/',views.gst_details,name='gst_details'),
    path('company_tds_details/<int:company_id>/',views.company_tds_details,name='company_tds_details'),
    path('company_tcs_details/<int:company_id>/',views.company_tcs_details,name='company_tcs_details'),
    path('vat_details/<int:company_id>/',views.vat_details,name='vat_details'),
    path('excise_details/<int:company_id>/',views.excise_details,name='excise_details'),
    path('service_tax_details/<int:company_id>/',views.service_tax_details,name='service_tax_details'),
    path('service_tax_rate/<int:company_id>/',views.service_tax_rate,name='service_tax_rate'),
    path('payroll_statutory_details/<int:company_id>/',views.payroll_statutory_details,name='payroll_statutory_details'),
    path('merchant_profile_details/<int:company_id>/',views.merchant_profile_details,name='merchant_profile_details'),
    path('multiple_address_list/<int:company_id>/',views.multiple_address_list,name='multiple_address_list'),
    path('create_multiple_address/<int:company_id>/',views.create_multiple_address,name='create_multiple_address'),
    path('gst_rate_details/<int:company_id>/',views.gst_rate_details,name='gst_rate_details'),

    path('create_company_fun/',views.create_company_fun,name='create_company_fun'),
    path('create_gst_details/<int:company_id>/', views.create_gst_details, name='create_gst_details'),
    path('create_gst_rate_details/<int:company_id>/',views.create_gst_rate_details,name='create_gst_rate_details'),
    path('create_tds_details/<int:company_id>/',views.create_tds_details,name='create_tds_details'),
    path('create_tcs_collector_details/<int:company_id>/',views.create_tcs_collector_details,name='create_tcs_collector_details'),
    path('create_vat_details/<int:company_id>/',views.create_vat_details,name='create_vat_details'),
    path('create_excise_details/<int:company_id>/',views.create_excise_details,name='create_excise_details'),
    path('create_service_tax_details/<int:company_id>/',views.create_service_tax_details,name='create_service_tax_details'),
    path('create_service_tax_rate_details/<int:company_id>/',views.create_service_tax_rate_details,name='create_service_tax_rate_details'),
    path('create_payroll_statutory_details/<int:company_id>/',views.create_payroll_statutory_details,name='create_payroll_statutory_details'),
    path('create_multiple_company_address/<int:company_id>/',views.create_multiple_company_address,name='create_multiple_company_address'),
    path('create_merchant_profile/<int:company_id>/',views.create_merchant_profile,name='create_merchant_profile'),
    path('save_company_features/',views.save_company_features,name='save_company_features'),

    path('dashboard/',views.dashboard,name='dashboard'),
    path('save_date_range/',views.save_date_range,name='save_date_range'),
    path('save_current_date/',views.save_current_date,name='save_current_date'),
    path('alter_company/',views.alter_company,name='alter_company'),

    path('create_new_state_alter/',views.create_new_state_alter,name='create_new_state_alter'),
    path('create_new_country_alter/',views.create_new_country_alter,name='create_new_country_alter'),
    path('alter_company_fun/<int:company_id>/',views.alter_company_fun,name='alter_company_fun'),

    path('change_company/',views.change_company,name='change_company'),
    path('select_company/',views.select_company,name='select_company'),
    path('tally_netuser/',views.tally_netuser,name='tally_netuser'),
    path('shut_company/',views.shut_company,name='shut_company'),
    path('security_user_access/',views.security_user_access,name='security_user_access'),
    path('tally_vault/',views.tally_vault,name='tally_vault'),
    path('create_tally_vault_setting/',views.create_tally_vault_setting,name='create_tally_vault_setting'),
    path('verify_tally_vault_password/',views.verify_tally_vault_password,name='verify_tally_vault_password'),

    path('alter_company_features/',views.alter_company_features,name='alter_company_features'),
    path('update_company_features/',views.update_company_features,name='update_company_features'),

    path('create_new_state_gst/',views.create_new_state_gst,name='create_new_state_gst'),
    path('create_new_state_vat/',views.create_new_state_vat,name='create_new_state_vat'),
    path('create_new_state_excise/',views.create_new_state_excise,name='create_new_state_excise'),

    path('LogOut/',views.LogOut,name='LogOut'),
    path('set_default_states_and_countries/',views.set_default_states_and_countries,name='set_default_states_and_countries'),



    #second work
    path('update_effective_date/',views.update_effective_date,name='update_effective_date'),
    path('gst_effective_date/<int:company_id>/', views.gst_effective_date, name='gst_effective_date'),
    path('save_effective_date/',views.save_effective_date,name='save_effective_date'),
    path('gst_settings/<int:company_id>/',views.gst_settings,name='gst_settings'),
    path('save_gst_return_types/',views.save_gst_return_types,name='save_gst_return_types'),
    path('slab_based_tax_rate/<int:company_id>/',views.slab_based_tax_rate,name='slab_based_tax_rate'),
    path('save_slab_rates/',views.save_slab_rates,name='save_slab_rates'),
    path('tds_person_responsible_details/<int:company_id>/',views.tds_person_responsible_details,name='tds_person_responsible_details'),
    path('save_tds_person_responsible_details/',views.save_tds_person_responsible_details,name='save_tds_person_responsible_details'),
    path('tds_person_create_new_state/',views.tds_person_create_new_state,name='tds_person_create_new_state'),
    path('tcs_person_responsible_details/<int:company_id>/',views.tcs_person_responsible_details,name='tcs_person_responsible_details'),
    path('save_tcs_person_responsible_details/',views.save_tcs_person_responsible_details,name='save_tcs_person_responsible_details'),
    path('tcs_person_create_new_state/',views.tcs_person_create_new_state,name='tcs_person_create_new_state'),
    path('vat_tax_rate_details/<int:company_id>/',views.vat_tax_rate_details,name='vat_tax_rate_details'),
    path('create_vat_tax_rate/<int:company_id>/',views.create_vat_tax_rate,name='create_vat_tax_rate'),
    path('excise_tariff_details/<int:company_id>/',views.excise_tariff_details,name='excise_tariff_details'),
    path('create_excise_tariff/<int:company_id>/',views.create_excise_tariff,name='create_excise_tariff'),
    path('create_new_user/',views.create_new_user,name='create_new_user'),
    path('security_settings_view/',views.security_settings_view,name='security_settings_view'),
    path('gst_classification/<int:company_id>/',views.gst_classification,name='gst_classification'),
    path('create_classification/',views.create_classification,name='create_classification'),
    # path('add_slab_rates//<int:classification_id>/slabrates/',views.add_slab_rates,name='add_slab_rates')
    
    path('outstanding_ledgers/',views.outstanding_ledgers,name='outstanding_ledgers'),
    path('outstanding_groups/',views.outstanding_groups,name='outstanding_groups'),
    path('masters/cost_categories/',views.cost_categories_view,name='cost_categories'),
    path('masters/currencies/',views.currencies_view,name='currencies'),
    path('masters/scenarios/',views.scenarios_view,name='scenarios'),
    path("masters/cost-categories/<int:pk>/edit/", views.edit_cost_category, name="edit_cost_category"),
    path("masters/currencies/<int:pk>/edit/", views.edit_currencies, name="edit_currencies"),
    path("masters/scenarios/<int:pk>/edit/", views.edit_scenarios, name="edit_scenarios"),
    path('masters/units/',views.units_view,name='units_view'),
    path('masters/godowns/',views.godowns_view,name='godowns_view'),
    path("masters/units/<int:pk>/edit/", views.edit_units, name="edit_units"),
    path("masters/godowns/<int:pk>/edit/", views.edit_godowns, name="edit_godowns"),
    path('masters/compound_units/<int:unit_id>/edit/',views.edit_compound_units,name='edit_compound_units'),
    path('godown/create/', views.godown_create, name='godown_create'),
    path('masters/unit_create/<int:unit_id>/', views.unit_create, name='unit_create'),

    
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
